n1=float(input('Digite sua nota do 1ºBimestre:'))
n2=float(input('Do 2º:'))
n3=float(input('3º:'))
n4=float(input('E por último do 4º:'))
print(f'De acordo com as notas dos 4 bimestres, {n1}, {n2}, {n3} e {n4}, respectivamente, calculando a média, sua nota final será {(n1+n2+n3+n4)/4:.1f}!')